# Service Account for Argo CD Image Updater with IRSA (IAM Roles for Service Accounts)
# This allows Image Updater to authenticate with AWS ECR using IAM roles instead of static credentials
#
# SETUP:
#   1. Create IAM role for Image Updater (via Terraform or manually)
#   2. Update the eks.amazonaws.com/role-arn annotation below with your IAM role ARN
#   3. Apply this file: kubectl apply -f argocd/image-updater-service-account.yaml
#   4. Update Image Updater deployment to use this Service Account

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    # IRSA: IAM Role ARN for Image Updater to access ECR
    # This placeholder will be replaced by GitHub Actions workflow or deployment script
    # The actual ARN is stored in Parameter Store and injected dynamically
    # Format: arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>
    eks.amazonaws.com/role-arn: "${ARGOCD_IMAGE_UPDATER_ROLE_ARN}"
    # For non-EKS clusters, remove this annotation and use static credentials instead
